// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod lulu_logs {


#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_LOG_LEVEL: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_LOG_LEVEL: i8 = 5;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_LOG_LEVEL: [LogLevel; 6] = [
  LogLevel::Trace,
  LogLevel::Debug,
  LogLevel::Info,
  LogLevel::Warn,
  LogLevel::Error,
  LogLevel::Fatal,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct LogLevel(pub i8);
#[allow(non_upper_case_globals)]
impl LogLevel {
  pub const Trace: Self = Self(0);
  pub const Debug: Self = Self(1);
  pub const Info: Self = Self(2);
  pub const Warn: Self = Self(3);
  pub const Error: Self = Self(4);
  pub const Fatal: Self = Self(5);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 5;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Trace,
    Self::Debug,
    Self::Info,
    Self::Warn,
    Self::Error,
    Self::Fatal,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Trace => Some("Trace"),
      Self::Debug => Some("Debug"),
      Self::Info => Some("Info"),
      Self::Warn => Some("Warn"),
      Self::Error => Some("Error"),
      Self::Fatal => Some("Fatal"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for LogLevel {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for LogLevel {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<i8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for LogLevel {
    type Output = LogLevel;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<i8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for LogLevel {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for LogLevel {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    i8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for LogLevel {}
pub enum LogEntryOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct LogEntry<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for LogEntry<'a> {
  type Inner = LogEntry<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> LogEntry<'a> {
  pub const VT_TIMESTAMP: ::flatbuffers::VOffsetT = 4;
  pub const VT_LEVEL: ::flatbuffers::VOffsetT = 6;
  pub const VT_TYPE_: ::flatbuffers::VOffsetT = 8;
  pub const VT_DATA: ::flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    LogEntry { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args LogEntryArgs<'args>
  ) -> ::flatbuffers::WIPOffset<LogEntry<'bldr>> {
    let mut builder = LogEntryBuilder::new(_fbb);
    if let Some(x) = args.data { builder.add_data(x); }
    if let Some(x) = args.type_ { builder.add_type_(x); }
    if let Some(x) = args.timestamp { builder.add_timestamp(x); }
    builder.add_level(args.level);
    builder.finish()
  }


  #[inline]
  pub fn timestamp(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(LogEntry::VT_TIMESTAMP, None).unwrap()}
  }
  #[inline]
  pub fn level(&self) -> LogLevel {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<LogLevel>(LogEntry::VT_LEVEL, Some(LogLevel::Info)).unwrap()}
  }
  #[inline]
  pub fn type_(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(LogEntry::VT_TYPE_, None).unwrap()}
  }
  #[inline]
  pub fn data(&self) -> ::flatbuffers::Vector<'a, u8> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(LogEntry::VT_DATA, None).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for LogEntry<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("timestamp", Self::VT_TIMESTAMP, true)?
     .visit_field::<LogLevel>("level", Self::VT_LEVEL, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("type_", Self::VT_TYPE_, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("data", Self::VT_DATA, true)?
     .finish();
    Ok(())
  }
}
pub struct LogEntryArgs<'a> {
    pub timestamp: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub level: LogLevel,
    pub type_: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub data: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for LogEntryArgs<'a> {
  #[inline]
  fn default() -> Self {
    LogEntryArgs {
      timestamp: None, // required field
      level: LogLevel::Info,
      type_: None, // required field
      data: None, // required field
    }
  }
}

pub struct LogEntryBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> LogEntryBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_timestamp(&mut self, timestamp: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(LogEntry::VT_TIMESTAMP, timestamp);
  }
  #[inline]
  pub fn add_level(&mut self, level: LogLevel) {
    self.fbb_.push_slot::<LogLevel>(LogEntry::VT_LEVEL, level, LogLevel::Info);
  }
  #[inline]
  pub fn add_type_(&mut self, type_: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(LogEntry::VT_TYPE_, type_);
  }
  #[inline]
  pub fn add_data(&mut self, data: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(LogEntry::VT_DATA, data);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> LogEntryBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    LogEntryBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<LogEntry<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, LogEntry::VT_TIMESTAMP,"timestamp");
    self.fbb_.required(o, LogEntry::VT_TYPE_,"type_");
    self.fbb_.required(o, LogEntry::VT_DATA,"data");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for LogEntry<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("LogEntry");
      ds.field("timestamp", &self.timestamp());
      ds.field("level", &self.level());
      ds.field("type_", &self.type_());
      ds.field("data", &self.data());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `LogEntry`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_log_entry_unchecked`.
pub fn root_as_log_entry(buf: &[u8]) -> Result<LogEntry<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<LogEntry>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `LogEntry` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_log_entry_unchecked`.
pub fn size_prefixed_root_as_log_entry(buf: &[u8]) -> Result<LogEntry<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<LogEntry>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `LogEntry` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_log_entry_unchecked`.
pub fn root_as_log_entry_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<LogEntry<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<LogEntry<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `LogEntry` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_log_entry_unchecked`.
pub fn size_prefixed_root_as_log_entry_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<LogEntry<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<LogEntry<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a LogEntry and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `LogEntry`.
pub unsafe fn root_as_log_entry_unchecked(buf: &[u8]) -> LogEntry<'_> {
  unsafe { ::flatbuffers::root_unchecked::<LogEntry>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed LogEntry and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `LogEntry`.
pub unsafe fn size_prefixed_root_as_log_entry_unchecked(buf: &[u8]) -> LogEntry<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<LogEntry>(buf) }
}
#[inline]
pub fn finish_log_entry_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<LogEntry<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_log_entry_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<LogEntry<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod LuluLogs
