// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod lulu_export {

pub enum LogRecordOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct LogRecord<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for LogRecord<'a> {
  type Inner = LogRecord<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> LogRecord<'a> {
  pub const VT_TOPIC: ::flatbuffers::VOffsetT = 4;
  pub const VT_PAYLOAD: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    LogRecord { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args LogRecordArgs<'args>
  ) -> ::flatbuffers::WIPOffset<LogRecord<'bldr>> {
    let mut builder = LogRecordBuilder::new(_fbb);
    if let Some(x) = args.payload { builder.add_payload(x); }
    if let Some(x) = args.topic { builder.add_topic(x); }
    builder.finish()
  }

  #[inline]
  pub fn topic(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(LogRecord::VT_TOPIC, None).unwrap() }
  }
  #[inline]
  pub fn payload(&self) -> ::flatbuffers::Vector<'a, u8> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(LogRecord::VT_PAYLOAD, None).unwrap() }
  }
}

impl ::flatbuffers::Verifiable for LogRecord<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("topic", Self::VT_TOPIC, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("payload", Self::VT_PAYLOAD, true)?
     .finish();
    Ok(())
  }
}

pub struct LogRecordArgs<'a> {
  pub topic:   Option<::flatbuffers::WIPOffset<&'a str>>,
  pub payload: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for LogRecordArgs<'a> {
  #[inline]
  fn default() -> Self {
    LogRecordArgs {
      topic:   None, // required field
      payload: None, // required field
    }
  }
}

pub struct LogRecordBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> LogRecordBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_topic(&mut self, topic: ::flatbuffers::WIPOffset<&'b str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(LogRecord::VT_TOPIC, topic);
  }
  #[inline]
  pub fn add_payload(&mut self, payload: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(LogRecord::VT_PAYLOAD, payload);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> LogRecordBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    LogRecordBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<LogRecord<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, LogRecord::VT_TOPIC, "topic");
    self.fbb_.required(o, LogRecord::VT_PAYLOAD, "payload");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for LogRecord<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("LogRecord");
    ds.field("topic", &self.topic());
    ds.field("payload", &self.payload());
    ds.finish()
  }
}

// ---------------------------------------------------------------------------

pub enum LuluExportFileOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct LuluExportFile<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for LuluExportFile<'a> {
  type Inner = LuluExportFile<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> LuluExportFile<'a> {
  pub const VT_VERSION: ::flatbuffers::VOffsetT = 4;
  pub const VT_RECORDS: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    LuluExportFile { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args LuluExportFileArgs<'args>
  ) -> ::flatbuffers::WIPOffset<LuluExportFile<'bldr>> {
    let mut builder = LuluExportFileBuilder::new(_fbb);
    if let Some(x) = args.records { builder.add_records(x); }
    builder.add_version(args.version);
    builder.finish()
  }

  #[inline]
  pub fn version(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(LuluExportFile::VT_VERSION, Some(1)).unwrap() }
  }
  #[inline]
  pub fn records(&self) -> ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<LogRecord<'a>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<LogRecord>>>>(LuluExportFile::VT_RECORDS, None).unwrap() }
  }
}

impl ::flatbuffers::Verifiable for LuluExportFile<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u32>("version", Self::VT_VERSION, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<LogRecord>>>>("records", Self::VT_RECORDS, true)?
     .finish();
    Ok(())
  }
}

pub struct LuluExportFileArgs<'a> {
  pub version: u32,
  pub records: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<LogRecord<'a>>>>>,
}
impl<'a> Default for LuluExportFileArgs<'a> {
  #[inline]
  fn default() -> Self {
    LuluExportFileArgs {
      version: 1,
      records: None, // required field
    }
  }
}

pub struct LuluExportFileBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> LuluExportFileBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_version(&mut self, version: u32) {
    self.fbb_.push_slot::<u32>(LuluExportFile::VT_VERSION, version, 1);
  }
  #[inline]
  pub fn add_records(&mut self, records: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, ::flatbuffers::ForwardsUOffset<LogRecord<'b>>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(LuluExportFile::VT_RECORDS, records);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> LuluExportFileBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    LuluExportFileBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<LuluExportFile<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, LuluExportFile::VT_RECORDS, "records");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for LuluExportFile<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("LuluExportFile");
    ds.field("version", &self.version());
    ds.field("records", &self.records());
    ds.finish()
  }
}

#[inline]
/// Verifies that a buffer of bytes contains a `LuluExportFile` and returns it.
pub fn root_as_lulu_export_file(buf: &[u8]) -> Result<LuluExportFile<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<LuluExportFile>(buf)
}

#[inline]
/// Assumes, without verification, that a buffer of bytes contains a LuluExportFile and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `LuluExportFile`.
pub unsafe fn root_as_lulu_export_file_unchecked(buf: &[u8]) -> LuluExportFile<'_> {
  unsafe { ::flatbuffers::root_unchecked::<LuluExportFile>(buf) }
}

} // pub mod lulu_export
